const Images = {
  logo: require('../Assets/Images/logo.png'),
  backButton: require('../Assets/Images/backbutton.png'),
  menuButton: require('../Assets/Images/menu.png'),
  qrCode: require('../Assets/Images/qrCode.png'),
  search: require('../Assets/Images/search128.png'),
  product: require('../Assets/Images/product.png'),
  heart: require('../Assets/Images/heart.png'),
  kangaroo: require('../Assets/Images/kangaroo.png'),
  map: require('../Assets/Images/map.png'),
  ship: require('../Assets/Images/ship.png'),
  p1: require('../Assets/Images/ferrero.png'),
  p2: require('../Assets/Images/coke.png'),
  emptyHeart: require('../Assets/Images/emptyHeart.png'),
  filledHeart: require('../Assets/Images/filledHeart.png'),
  dhome: require('../Assets/Images/home.png'),
  dshopping: require('../Assets/Images/shopping.png'),
  dbarcode: require('../Assets/Images/barcode.png'),
  dsearch: require('../Assets/Images/searchc.png'),
  dproduct: require('../Assets/Images/productc.png'),
  dlogout: require('../Assets/Images/logout.png'),
  fb: require('../Assets/Images/facebook-app-symbol.png'),
  filter: require('../Assets/Images/filter.png'),
  scan: require('../Assets/Images/scan.png'),
  checked: require('../Assets/Images/checked.png'),
  unchecked: require('../Assets/Images/unchecked.png'),
  plus: require('../Assets/Images/plus.png'),
  close: require('../Assets/Images/cancel.png'),
  dropDownIcon: require('../Assets/Images/dropdown.png'),
  rightSign: require('../Assets/Images/check.png')
}

export default Images
